plugins:
  - jekyll-relative-links
  - jekyll-theme-gitbook
title: Chargeprice API Documentation
theme: jekyll-theme-gitbook
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-dinky